// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aumktnfxomrxuayipcbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1bWt0bmZ4b21yeHVheWlwY2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTA5MDMsImV4cCI6MjA3MjUyNjkwM30.9AF-_rQTg5IfiSmrBfhPjUNRvN7j5kmppkTmPsC5s4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});